// Package accesscontract defines the cluster-owned Phase 2 route identity.
// It is shared by the controller and authorizer and deliberately stays out of
// the public Cell API.
package accesscontract

import (
	"errors"
	"fmt"
	"strings"

	"k8s.io/apimachinery/pkg/util/validation"

	"github.com/GuoMonth/dsh-isolated-runtime/internal/cellcontract"
)

// EnvoyOAuthCookieNames are the base names of the credential cookies emitted
// by the OAuth2 filter generated by the pinned Envoy Gateway release. Envoy
// Gateway appends a 32-bit FNV-1a hash formatted with %x (1–8 hex digits,
// without zero padding) to each current default name. The exact
// legacy names are also reserved so a forged or stale credential-shaped cookie
// cannot cross the trusted ingress boundary into a Cell.
var EnvoyOAuthCookieNames = [...]string{
	"AccessToken",
	"BearerToken",
	"OauthHMAC",
	"OauthExpires",
	"IdToken",
	"RefreshToken",
	"OauthNonce",
	"CodeVerifier",
}

// IsEnvoyOAuthCookie reports whether name is reserved for Envoy OAuth2 state.
// Filtering case-insensitively also rejects malformed variants instead of
// passing possible credentials on to DSH.
func IsEnvoyOAuthCookie(name string) bool {
	for _, reserved := range EnvoyOAuthCookieNames {
		if strings.EqualFold(name, reserved) {
			return true
		}
		if hasEnvoyCookieSuffix(name, reserved) {
			return true
		}
	}
	return false
}

func hasEnvoyCookieSuffix(name, base string) bool {
	if len(name) < len(base)+2 || len(name) > len(base)+9 || !strings.EqualFold(name[:len(base)], base) || name[len(base)] != '-' {
		return false
	}
	for _, character := range name[len(base)+1:] {
		if (character < '0' || character > '9') &&
			(character < 'a' || character > 'f') &&
			(character < 'A' || character > 'F') {
			return false
		}
	}
	return true
}

// Mode separates a platform-owned ingress from runtime-owned direct routes.
type Mode string

const (
	ModeStandalone Mode = "standalone"
	ModePlatform   Mode = "platform"
)

type Config struct {
	Mode              Mode
	GatewayName       string
	GatewayNamespace  string
	GatewaySection    string
	BaseDomain        string
	ExternalHTTPSPort int
}

func (c Config) Enabled() bool {
	return c.Mode != ModePlatform && strings.TrimSpace(c.GatewayName) != ""
}

func (c Config) HasPublicAuthority() bool {
	return c.Mode == ModePlatform || c.Enabled()
}

func (c Config) Validate() error {
	if c.Mode != "" && c.Mode != ModeStandalone && c.Mode != ModePlatform {
		return fmt.Errorf("invalid access mode %q: use standalone or platform", c.Mode)
	}
	if c.Mode == ModePlatform && strings.TrimSpace(c.GatewayName) != "" {
		return errors.New("platform access conflicts with gateway-name: configure platform routing separately")
	}
	if !c.HasPublicAuthority() {
		if strings.TrimSpace(c.BaseDomain) != "" {
			return errors.New("gateway name is required when base domain is configured")
		}
		return nil
	}
	for field, value := range map[string]string{
		"gateway name":      c.GatewayName,
		"gateway namespace": c.GatewayNamespace,
		"gateway section":   c.GatewaySection,
		"base domain":       c.BaseDomain,
	} {
		if c.Mode != ModePlatform && strings.TrimSpace(value) == "" {
			return fmt.Errorf("%s is required when Gateway routing is enabled", field)
		}
	}
	if c.Mode != ModePlatform {
		if problems := validation.IsDNS1123Subdomain(c.GatewayName); len(problems) != 0 {
			return fmt.Errorf("invalid gateway name: %s", strings.Join(problems, "; "))
		}
		if problems := validation.IsDNS1123Subdomain(c.GatewayNamespace); len(problems) != 0 {
			return fmt.Errorf("invalid gateway namespace: %s", strings.Join(problems, "; "))
		}
		if problems := validation.IsDNS1123Label(c.GatewaySection); len(problems) != 0 {
			return fmt.Errorf("invalid gateway section: %s", strings.Join(problems, "; "))
		}
	}
	if strings.HasSuffix(c.BaseDomain, ".") {
		return errors.New("base domain must not have a trailing dot")
	}
	if problems := validation.IsDNS1123Subdomain(c.BaseDomain); len(problems) != 0 {
		return fmt.Errorf("invalid base domain: %s", strings.Join(problems, "; "))
	}
	const sampleUID = "00000000-0000-0000-0000-000000000000"
	if problems := validation.IsDNS1123Subdomain(c.Hostname(sampleUID)); len(problems) != 0 {
		return fmt.Errorf("base domain is too long for a Cell hostname: %s", strings.Join(problems, "; "))
	}
	if c.Port() < 1 || c.Port() > 65535 {
		return errors.New("external HTTPS port must be between 1 and 65535")
	}
	return nil
}

func (c Config) Port() int {
	if c.ExternalHTTPSPort == 0 {
		return 443
	}
	return c.ExternalHTTPSPort
}

func (c Config) Hostname(uid string) string {
	return cellcontract.PublicHostname(c.BaseDomain, uid)
}

func (c Config) Authority(uid string) string {
	return cellcontract.PublicAuthority(c.BaseDomain, uid, c.Port())
}
