// Package accesscontract defines credential-cookie filtering at the application seam.
package accesscontract

import "strings"

// EnvoyOAuthCookieNames are the base names of the credential cookies emitted
// by the OAuth2 filter generated by the pinned Envoy Gateway release. Envoy
// Gateway appends a 32-bit FNV-1a hash formatted with %x (1–8 hex digits,
// without zero padding) to each current default name. The exact
// legacy names are also reserved so a forged or stale credential-shaped cookie
// cannot cross the trusted ingress boundary into a Cell.
var EnvoyOAuthCookieNames = [...]string{
	"AccessToken",
	"BearerToken",
	"OauthHMAC",
	"OauthExpires",
	"IdToken",
	"RefreshToken",
	"OauthNonce",
	"CodeVerifier",
}

// IsEnvoyOAuthCookie reports whether name is reserved for Envoy OAuth2 state.
// Filtering case-insensitively also rejects malformed variants instead of
// passing possible credentials on to DSH.
func IsEnvoyOAuthCookie(name string) bool {
	for _, reserved := range EnvoyOAuthCookieNames {
		if strings.EqualFold(name, reserved) {
			return true
		}
		if hasEnvoyCookieSuffix(name, reserved) {
			return true
		}
	}
	return false
}

func hasEnvoyCookieSuffix(name, base string) bool {
	if len(name) < len(base)+2 || len(name) > len(base)+9 || !strings.EqualFold(name[:len(base)], base) || name[len(base)] != '-' {
		return false
	}
	for _, character := range name[len(base)+1:] {
		if (character < '0' || character > '9') &&
			(character < 'a' || character > 'f') &&
			(character < 'A' || character > 'F') {
			return false
		}
	}
	return true
}
