apiVersion: apps/v1
kind: Deployment
metadata:
  name: cell-operator
spec:
  template:
    spec:
      containers:
        - name: manager
          args:
            - --gateway-name=dsh
            - --gateway-namespace=dsh-system
            - --gateway-section-name=https
            - --base-domain=cells.example.com
            - --external-https-port=443
            - --enable-snapshots=true
            - --writer-stop-timeout=2m
            - --snapshot-timeout=30m
            - --metrics-bind-address=:8080
            - --cell-concurrency=4
            - --snapshot-concurrency=2
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
