version: "2"

run:
  timeout: 3m

linters:
  default: standard
  enable:
    - bodyclose

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/GuoMonth/dsh-isolated-runtime
