apiVersion: apps/v1
kind: Deployment
metadata:
  name: cell-authorizer
spec:
  template:
    spec:
      containers:
        - name: authorizer
          ports:
            - name: callback
              containerPort: 8080
            - name: health
              containerPort: 8081
            - name: grpc
              containerPort: 9001
            - name: metrics
              containerPort: 9090
