apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: manager-patch.yaml
  - path: authorizer-patch.yaml
  - target:
      kind: Deployment
      name: cell-operator
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --metrics-bind-address=:8080
  - target:
      kind: Deployment
      name: cell-authorizer
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --metrics-bind-address=:9090
