apiVersion: apps/v1
kind: Deployment
metadata:
  name: cell-operator
spec:
  template:
    spec:
      containers:
        - name: manager
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
