apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dsh-system
resources:
  - ../phase2
patches:
  - path: manager-patch.yaml
images:
  - name: controller
    newName: ghcr.io/guomonth/dsh-isolated-runtime-operator
    newTag: main
