apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - crds/dsh.isolated.io_runtimes.yaml
  - rbac/serviceaccount.yaml
  - rbac/role.yaml
  - rbac/rolebinding.yaml
  - deploy/deployment.yaml
  - deploy/service.yaml
