FROM --platform=$BUILDPLATFORM golang:1.27.1-bookworm@sha256:648f440f42a0958804efb24df176f806f9d353b41f1c0627f666428e40310f6b AS builder
ARG TARGETOS=linux
ARG TARGETARCH=amd64
WORKDIR /src
COPY test/e2e/phase4/fixture/main.go ./main.go
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH \
    go build -trimpath -ldflags='-s -w -buildid=' -o /out/cell-launcher ./main.go

FROM scratch
COPY --from=builder /out/cell-launcher /usr/local/bin/cell-launcher
USER 1000:1000
EXPOSE 8080 8081
ENTRYPOINT ["/usr/local/bin/cell-launcher"]
