FROM --platform=$BUILDPLATFORM golang:1.24-bookworm@sha256:1a6d4452c65dea36aac2e2d606b01b4a029ec90cc1ae53890540ce6173ea77ac AS builder
ARG TARGETOS=linux
ARG TARGETARCH=amd64
WORKDIR /src
COPY test/e2e/phase4/fixture/main.go ./main.go
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH \
    go build -trimpath -ldflags='-s -w -buildid=' -o /out/cell-launcher ./main.go

FROM scratch
COPY --from=builder /out/cell-launcher /usr/local/bin/cell-launcher
USER 1000:1000
EXPOSE 8080 8081
ENTRYPOINT ["/usr/local/bin/cell-launcher"]
