import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { resolve } from "node:path";
const baseline = JSON.parse(readFileSync(new URL("./baseline.json", import.meta.url)));
const root = process.argv[2];
if (!root) throw new Error("Usage: node compat/dsh/apply-patches.mjs NPM_INSTALL_ROOT");
const patch = baseline.distribution.settingsPatch;
const file = resolve(root, patch.file);
const input = readFileSync(file, "utf8");
const sha = value => createHash("sha256").update(value).digest("hex");
if (sha(input) !== patch.beforeSHA256) throw new Error("Unexpected official RC2 settings module; refusing patch");
const output = input.replace('const persistence = ctx.remote.$host.isLoopback ? "host" : "memory";', 'const persistence = "host";');
if (sha(output) !== patch.afterSHA256) throw new Error("Unexpected patched settings module");
writeFileSync(file, output);
